// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dmurglcfksmsjysuqhtl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRtdXJnbGNma3Ntc2p5c3VxaHRsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0MjMyNzcsImV4cCI6MjA3MTk5OTI3N30.86jqvf8pAzT9lCOzEdsZM6orAETIFxXc82XReyQCn2s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});